[colors]
draw_bold_text_with_bright_colors = true
#import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.yml"]

[colors.primary]
background = "#010010"
foreground = "#DBCEF1"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.6

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[terminal]

# [env]
# term = "xterm-256color"
