require("which-key").setup({
    preset = "modern",
    delay  = 300,
    icons  = { mappings = true },
    spec   = {
        { "<leader>f",  group = "Find",            icon = "" },
        { "<leader>ff", desc  = "Find Files" },
        { "<leader>fg", desc  = "Live Grep" },
        { "<leader>fb", desc  = "Buffers" },
        { "<leader>fh", desc  = "Help Tags" },
        { "<leader>fd", desc  = "Diagnostics" },
        { "<leader>fr", desc  = "LSP References" },
        { "<leader>fs", desc  = "Document Symbols" },
        { "<leader>fc", desc  = "Git Commits" },
        { "<leader>fo", desc  = "Recent Files" },
        { "<leader>fw", desc  = "Grep Word Under Cursor" },
        { "<leader>ft", desc  = "Find TODOs" },

        { "<leader>g",  group = "Git",             icon = "" },
        { "<leader>lg", desc  = "LazyGit" },
        { "<leader>hs", desc  = "Stage Hunk" },
        { "<leader>hr", desc  = "Reset Hunk" },
        { "<leader>hS", desc  = "Stage Buffer" },
        { "<leader>hu", desc  = "Undo Stage Hunk" },
        { "<leader>hR", desc  = "Reset Buffer" },
        { "<leader>hp", desc  = "Preview Hunk" },
        { "<leader>hb", desc  = "Blame Line" },
        { "<leader>hd", desc  = "Diff This" },

        { "<leader>x",  group = "Diagnostics",     icon = "" },
        { "<leader>xx", desc  = "Toggle Trouble" },
        { "<leader>xX", desc  = "Buffer Diagnostics" },
        { "<leader>xs", desc  = "Symbols" },
        { "<leader>xl", desc  = "LSP Panel" },
        { "<leader>xL", desc  = "Location List" },
        { "<leader>xQ", desc  = "Quickfix List" },

        { "<leader>c",  group = "Code",            icon = "" },
        { "<leader>ca", desc  = "Code Action" },
        { "<leader>cf", desc  = "Format" },
        { "<leader>cl", desc  = "Lint" },
        { "<leader>rn", desc  = "Rename Symbol" },

        { "<leader>t",  group = "Tree / Toggle",   icon = "" },
        { "<leader>tr", desc  = "Toggle File Tree" },
        { "<leader>tf", desc  = "Reveal File in Tree" },
        { "<leader>tg", desc  = "Git Status" },
        { "<leader>tb", desc  = "Buffers" },

        { "<leader>b",  group = "Buffer",          icon = "󰓩" },
        { "<leader>bd", desc  = "Close Buffer" },

        { "<leader>h",  group = "Git Hunks",       icon = "" },
        { "<leader>s",  desc  = "Replace Word Under Cursor" },
        { "<leader>u",  desc  = "Toggle Undotree" },
        { "<leader>e",  desc  = "Diagnostic Float" },
        { "<leader>ec", desc  = "Edit Config" },
        { "<leader>y",  desc  = "Yank to Clipboard" },
        { "<leader>Y",  desc  = "Yank Line to Clipboard" },
        { "<leader>d",  desc  = "Delete to Black Hole" },
        { "<leader>p",  desc  = "Paste Without Clobbering" },
        { "<leader>D",  desc  = "Type Definition" },
    },
})
