color0 #131313
color1 #ffb4ab
color2 #82cfff
color3 #b6c9d8
color4 #ccc1e9
color5 #82cfff
color6 #b6c9d8
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #82cfff
color11 #b6c9d8
color12 #ccc1e9
color13 #82cfff
color14 #b6c9d8
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #82cfff
inactive_border_color #474747
url_color             #82cfff

active_tab_foreground   #00344b
active_tab_background   #82cfff
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
