color0 #131313
color1 #ffb4ab
color2 #9ed67c
color3 #bdcbaf
color4 #a0cfcf
color5 #9ed67c
color6 #bdcbaf
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #9ed67c
color11 #bdcbaf
color12 #a0cfcf
color13 #9ed67c
color14 #bdcbaf
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #9ed67c
inactive_border_color #474747
url_color             #9ed67c

active_tab_foreground   #143800
active_tab_background   #9ed67c
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
