vim.g.mapleader = ' '
vim.g.localleader = ' '
vim.opt.termguicolors = true
vim.opt.number =true
vim.opt.numberwidth = 1
vim.opt.relativenumber = true
vim.opt.smarttab = true
vim.opt.smartindent =true
vim.opt.expandtab=true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.autoindent = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.scrolloff = 8
vim.api.nvim_set_hl(0, 'LineNr', { fg='white' })
